### ISSUE TITLE
[Bug] Home screen summary for Radarr/Sonarr longer than three digits gets wrapped

### ISSUE THREAD

**Issue by hwwilliams** [JagandeepBrar/LunaSea#1]
Just wanted to mention this small thing, haven't noticed anything else.

![image](https://user-images.githubusercontent.com/20447447/71387556-7086ff80-25c2-11ea-8742-d10b8cdf6e2d.png)

**Comment by JagandeepBrar** [comment]
Noted, I will get this fixed for the next release!

A sidenote, but I have also adjusted the quicklinks so that they expand to fill the full row correctly with any amount of widgets.

**Comment by JagandeepBrar** [comment]
Been fixed, will be live in the next update by the end of this week.

![IMG_0581](https://user-images.githubusercontent.com/3048295/71424879-379b6900-265c-11ea-8879-da0d0f9bdb05.png)

**Comment by JagandeepBrar** [comment]
Fixed with the release of v0.2.0+1.
