### ISSUE TITLE
[Bug] total number of movies / series

### ISSUE THREAD

**Issue by Silent-Remux** [JagandeepBrar/LunaSea#100]
**Describe the Bug**

Large radarr / sonarr libraries cause the total number of movies / series to say `-1`

**Comment by Silent-Remux** [comment]
![A02445B9-9645-4DB1-89D8-68970FC956DB](https://user-images.githubusercontent.com/16107603/73493306-65d23e00-43aa-11ea-90bf-55cc971fa375.png)

**Comment by JagandeepBrar** [comment]
That's strange, is there any error that shows up in the logs?

It only returns -1 on some kind of error. I have seen some users who have >10000 movies and I personally have about 700 shows on Sonarr and it displays it correctly. How much do you have in each respectively server?

**Comment by Silent-Remux** [comment]
> That's strange, is there any error that shows up in the logs?
> 
> It only returns -1 on some kind of error. I have seen some users who have >10000 movies and I personally have about 700 shows on Sonarr and it displays it correctly. How much do you have in each respectively server?

More than that :)

Like a lot more.

**Comment by JagandeepBrar** [comment]
@Silent-Remux Can you go to Settings -> Logs -> Export Logs and send me the file? You can either email it directly to hello@lunasea.app if you don't want anyone else to see the logs, or you can post the file here!

**Comment by JagandeepBrar** [comment]
Hey @Silent-Remux, I never got any logs or anything from you to move forward on this issue. Do you have a chance to send me something soon?

You can email them to me at hello@lunasea.app!

**Comment by Silent-Remux** [comment]
> Hey @Silent-Remux, I never got any logs or anything from you to move forward on this issue. Do you have a chance to send me something soon?
> 
> You can email them to me at [hello@lunasea.app](mailto:hello@lunasea.app)!

It's been working with the testflight builds. Would be good to cache it though so it doesn't take so long to appear.

**Comment by JagandeepBrar** [comment]
@Silent-Remux after the next release, I am going to be focusing on code clean and implementing methods for caching data!

Since it is working fro you now though I will be closing this issue.
