### ISSUE TITLE
[Feature Request] manual and auto search options from Sonarr

### ISSUE THREAD

**Issue by Nach0-Stallion** [JagandeepBrar/LunaSea#101]
Hi.
Loving the app, but I have a few requests (I’ll post them individually)
In Radarr when I goto search for a movie it asks to use manual or automatic search, however in Sonarr (V3) if I tap the magnifying glass it just auto searches
Maybe if we could drill down to the episode info and have a manual or auto button rather than just season list overview?
Or maybe it’s a V3 limitation?

**Comment by simonk83** [comment]
You can long hold the magnifying glass and it takes you to manual mode 👍🏻

**Comment by Nach0-Stallion** [comment]
Freaking awesome!

Thank you!
