### ISSUE TITLE
[Feature Request] Calendar on Homepage

### ISSUE THREAD

**Issue by JagandeepBrar** [JagandeepBrar/LunaSea#109]
**Describe the solution you'd like**
Add a calendar to the homepage that allows a user to see upcoming content for all of their services in one screen.

**Additional context**
https://www.reddit.com/r/LunaSeaApp/comments/ex3262/calendar_on_homepage/

**Comment by simonk83** [comment]
Love it

**Comment by JagandeepBrar** [comment]
Now merged into `v1.1.0`, will be in the next TestFlight in the coming hours.
