### ISSUE TITLE
[Feature Request] Sonarr - A way to get to the actual show from the Upcoming tab

### ISSUE THREAD

**Issue by simonk83** [JagandeepBrar/LunaSea#119]
Clicking on a show from the Upcoming tab takes you to the latest Season, but there’s no way to get to the actual show from there. You have to click out, go to the catalogue tab, and search for it.

**Comment by JagandeepBrar** [comment]
This has now been implemented and is in the branch `v1.1.0`. Will be live in the next TestFlight build soon!

You simply have to long-press on the tile and it will take you to the root of that entry (Lidarr -> Artist page, Sonarr -> Show page). Radarr remains the same as it does not have nested releases (artists have albums, TV shows have episodes, but movies are movies).

**Comment by JagandeepBrar** [comment]
Now available in TestFlight build: v1.1.0 (22)!
