### ISSUE TITLE
[Feature Request] Add the option to physically delete shows/movies, not just remove the listing 

### ISSUE THREAD

**Issue by simonk83** [JagandeepBrar/LunaSea#120]
95% of the time, if I’m removing an item from Radarr/Sonarr, I’m done with it and also want to delete the files/folders. From memory there’s a setting you need to enable in -rr to allow that, and you should still pop up an “are you super sure” nag, but it’d be really nice to have. At the moment I have to load up the full service to delete stuff, or do it through something else (

**Comment by JagandeepBrar** [comment]
This has been implemented in TestFlight and be be accessed via a long hold of the episode tile when viewing the episodes!

**Comment by simonk83** [comment]
Thanks, just to be a bit more clear I’m mostly talking about this in Radarr:

![D8151CF9-F976-4304-ADAD-5A40130AE247](https://user-images.githubusercontent.com/518440/74113635-95c6e000-4bf9-11ea-9644-70eb53f86a29.jpeg)

Ideally I DO want to remove the files (and folder) when I’m removing a movie, or at least have the option to 👍🏻

**Comment by JagandeepBrar** [comment]
Yes I will adding this! In my late night sleepy state I misread the issue and closed it thinking it was for the ability to delete single episode files in Sonarr. This will be added for `v1.1.0`. :)

**Comment by simonk83** [comment]
Legend, thanks 😊

**Comment by JagandeepBrar** [comment]
Okay this has been merged into `v1.1.0` and will be in the next TestFlight release!

When deleting content from an -rr service, there will be a new button at the bottom "Delete + Files" to delete the files as well. It shows a secondary dialog to confirm the deletion of the media.

![IMG_0820](https://user-images.githubusercontent.com/3048295/74114634-ddedf000-4b70-11ea-96ad-8d5309a8784f.png)
