### ISSUE TITLE
[Feature Request] Show date and status of tv shows when adding new ones 

### ISSUE THREAD

**Issue by geekaroni** [JagandeepBrar/LunaSea#139]
**Describe the solution you'd like**
Show the year the show was created and if it’s still airing or not. I like to know if the show has ended or is still ongoing. This I can see in sonarr but not sure if the api allows it.

**Comment by JagandeepBrar** [comment]
The API does allow this and I’ll be adding it in the next release! Small and easy thing to add in :)

**Comment by JagandeepBrar** [comment]
This has now been added and is live in the TestFlight!

**Comment by JagandeepBrar** [comment]
My apologies, this has not been added yet but will be in the next TestFlight release!

**Comment by JagandeepBrar** [comment]
![IMG_0954](https://user-images.githubusercontent.com/3048295/76005687-ff709c00-5ed0-11ea-9291-08544adee86c.PNG)

Support for this has been added but is not currently live in a TestFlight release. It will be live this weekend (hopefully!) alongside support for indexers.

**Comment by JagandeepBrar** [comment]
This is now live in TestFlight v2.0.0 (33)!
