### ISSUE TITLE
[Feature Request] Create a Cydia Repository

### ISSUE THREAD

**Issue by JagandeepBrar** [JagandeepBrar/LunaSea#14]
Create a Cydia repository to allow users with jailbroken devices to easily install LunaSea.

**Comment by JagandeepBrar** [comment]
If there are any users out there who have jailbroken devices who would like to test a repository in the near future, please comment below so we can get in touch!

**Comment by KylePetko** [comment]
I can test it. I have a jail broken iPhone X and use checkra1n to jailbreak.

**Comment by JagandeepBrar** [comment]
@KylePetko thanks for the offer!

Was able to get my hands on an older iPhone, and setup the repository! A Cydia repository is now available here: https://repo.lunasea.app

I did testing on one device, so if any issues pop up please let me know!
