### ISSUE TITLE
[Feature Request] Option to keep the dropdowns in the sidebar permanently expanded

### ISSUE THREAD

**Issue by simonk83** [JagandeepBrar/LunaSea#141]
As there’s two seperate sections (Automation and Clients), but not really enough items in there to fill the screen), my preference would be to keep it all expanded as it just saves a click switching between items.

**Comment by JagandeepBrar** [comment]
I agree, for the time being that there are not an excessive amount of services enabled in LunaSea I will keep both of the dropdowns initially expanded. I have merged that change into `v1.1.0`, and will be in the next TextFlight & release!
