### ISSUE TITLE
[Feature Request] Tiny request to highlight the current day in the Calendar view

### ISSUE THREAD

**Issue by simonk83** [JagandeepBrar/LunaSea#149]
Just a nice QoL thing :)  Calendar looks great, thanks.

**Comment by JagandeepBrar** [comment]
Do you mean the selected date or today's date? Because the selected date is already highlighted.

**Comment by simonk83** [comment]
Today’s date 👍🏻

**Comment by geekaroni** [comment]
See my issue here about also adding the day to this page too. https://github.com/JagandeepBrar/LunaSea/issues/153

**Comment by JagandeepBrar** [comment]
This has now been added and is live in the TestFlight!
