### ISSUE TITLE
[Bug] FloatingActionButton covers actions on ListTiles

### ISSUE THREAD

**Issue by elmstreetvictim** [JagandeepBrar/LunaSea#15]
**Describe the solution you'd like**
The eyeball button covers the monitored status flag when there is a long list of items within Radarr and probably sonarr also. 

Wanted to unmonitor an item at the bottom of a list and I couldn’t tap the flag on iPhone XS Max. Had to unmonitor the item above it (which I didn’t want) in order to access the one at the bottom of the list. Then I had to re-monitor the other one. 

Perhaps add padding to the bottom of the scroll view in order to see every item completely.

**Comment by JagandeepBrar** [comment]
I tagged this as a bug, since this isn't the intended action.

I will be adding a ScrollController to watch the scrolling state of the list and hide the floating action button when a user starts to scroll down, and unhide the button when scrolling up.

**Comment by JagandeepBrar** [comment]
This has been fixed and will be included in the next build.
