### ISSUE TITLE
[Feature Request] Ability to work wth HTTP Basic Auth

### ISSUE THREAD

**Issue by theg00s3** [JagandeepBrar/LunaSea#16]
**Describe the solution you'd like**
The ability to type in the HTTP Basic Auth credentials in the app

**Additional context**
I have my nginx setup to prompt for credentials, so I can't use this app until I can authenticate myself in app

**Comment by Lasikie** [comment]
See this


https://github.com/JagandeepBrar/LunaSea/issues/5#issuecomment-569838280

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by theg00s3** [comment]
I think I found out why that wasn't working for me with Sonarr. I'm running Sonarr v3, which has a different API scheme to Sonarr v2
