### ISSUE TITLE
[Feature Request] Display year in search results

### ISSUE THREAD

**Issue by KarlSeaton** [JagandeepBrar/LunaSea#163]
When searching for a movie or TV show to add, it can be hard finding the correct item when there are multiple with the same name. It would be great if you showed the year next to the title to help differentiate between them.

**Comment by JagandeepBrar** [comment]
This has actually already been implemented in the TestFlight releases and will be live in the 2.0.0 update later this month!

https://github.com/JagandeepBrar/LunaSea/issues/139#issuecomment-595338737
