### ISSUE TITLE
[Bug] Warning about automatically selecting architechtures

### ISSUE THREAD

**Issue by myusuf3** [JagandeepBrar/LunaSea#19]
There is the warning and would like app developer to clear it so we dont see any warnings. I am fairly impressed that the only one present. 

**To Reproduce**
Run Xcode and click the warning label. Screenshot provided above. 

**Expected Behaviour**
No warnings or errors

**Screenshots**
![image](https://user-images.githubusercontent.com/156825/71644658-1d840b00-2c9a-11ea-996c-0f8af964744c.png)

**Versions**
Master

**Additional context**
Not a huge deal but would love to clear it out.

**Comment by myusuf3** [comment]
at the very least is it safe to perform the change?

**Comment by JagandeepBrar** [comment]
I also get these warnings, but I would leave them since the Pods are not my code, but packages I have imported. You can attempt to perform the changes and see if it still compiles, but I personally would rather leave them incase they cause non-obvious internal errors.
