### ISSUE TITLE
[Feature Request] Way to sort media by size to facilitate deletion. 

### ISSUE THREAD

**Issue by myusuf3** [JagandeepBrar/LunaSea#20]
**Describe the solution you'd like**
I would like to see what is taking up most storage and use that as a way to delete it. 

**Additional context**
Right now in order to do this, it isn't that bad but it would be nice to sort by size and use that as a way to remove things I know I dont need in 4K or that I wont need stored.

**Comment by JagandeepBrar** [comment]
Could you give some more context for the request? Which service would you like to see what is using up space?

I am not sure if any of the 3 "rr" services support sorting the files by size, but I would like to understand the request more first.

**Comment by myusuf3** [comment]
so lets say i have 10 movies and they are taking up X space. I would like to sort by size and then be able to use that as a way to delete things as needed to address space concerns.

**Comment by JagandeepBrar** [comment]
Ah, I understand now! I am going to close this issue since #4 is requesting the same thing, it will be implemented at a future date!

**Comment by myusuf3** [comment]
I would disagree, here you are already listing the sizes for each of the shows with initial request, all I am asking for it a way to sort by it.

**Comment by JagandeepBrar** [comment]
I'll try to get some basic sorting (including by size) implemented for the next release. If not the next release, I'll add it for the follow-up after that!

Just need to figure out how to do it from UI-side, but you're right in that it should be simple.

**Comment by JagandeepBrar** [comment]
Because of how long v0.4.0+1 has taken to come out, I have decided to push it back one release and release it in v0.4.1+1.

**Comment by JagandeepBrar** [comment]
This has now been implemented, in `v1.0.0` branch and will come in the next release! All 3 -rr services now have the ability to sort, via a button beside the search bar.

![IMG_0756](https://user-images.githubusercontent.com/3048295/73488801-3520e300-436f-11ea-8f67-e91d3bc03434.png)
