### ISSUE TITLE
[Bug] convert all character properly.

### ISSUE THREAD

**Issue by myusuf3** [JagandeepBrar/LunaSea#22]
**Describe the Bug**
convert all character properly.

**To Reproduce**
try to search a title with character like in the screenshot

**Expected Behaviour**
all characters should be included in search

**Screenshots**
![IMG_314D9B3D2567-1](https://user-images.githubusercontent.com/156825/71644898-0810e000-2c9e-11ea-8f2c-ac6a9acd8b4a.jpeg)

**Versions**
current master

**Comment by JagandeepBrar** [comment]
The search bar is just a mock searchbar as a little joke (mocking very old ways of finding megaupload files via google), so it doesn't impede functionality, but I do want to fix this visually.

**Comment by JagandeepBrar** [comment]
This been fixed and pushed to the repository, will be included in the next build/release.

![IMG_0615](https://user-images.githubusercontent.com/3048295/71695184-f818ff00-2d76-11ea-9c27-59315f020cc7.png)
