### ISSUE TITLE
[Bug] SABnzbd's history item stage_log can be a string

### ISSUE THREAD

**Issue by JagandeepBrar** [JagandeepBrar/LunaSea#289]
Sometimes a history entry from SABnzbd can have the `stage_log` value as an empty string, not a List of strings. In this scenario, it causes the entire history view to fail to load until that history entry is outside of the 200 item load range.

Should do type checks, if it is an empty string, mutate it to be a list of a single empty string.

**Comment by JagandeepBrar** [comment]
This will get fixed when SABnzbd's API is separated into its own package during its rework.

For now, and for how often it happens (a few times have been reported in the past year), I will just leave it as-is and do the type-checking in the separated package. This can easily be remedied by deleting the breaking history entry through the web GUI.

**Comment by IrPgFKS0** [comment]
When is the API rework scheduled to happen?

**Comment by JagandeepBrar** [comment]
@IrPgFKS0 Radarr is currently being upgraded, the clients (SAB and NZBGet) will happen after that.

**Comment by IrPgFKS0** [comment]
Ah ok, I thought you meant separation of the API client stream in LunaSea, thank you.

**Comment by JagandeepBrar** [comment]
@IrPgFKS0 The "upgrade" I mentioned will include exactly that.

**Comment by IrPgFKS0** [comment]
Thank you for confirming

**Comment by JagandeepBrar** [comment]
This has been resolved with the release of SABnzbd 3.7.1.
