### ISSUE TITLE
[Feature Request] Option to download things marked as blacklisted

### ISSUE THREAD

**Issue by elmstreetvictim** [JagandeepBrar/LunaSea#30]
Add a download button in each cell next to the blacklist icon. Just like manual searching with the radarr and sonarr webapps, there should be an option to overrule the blacklist and force a download anyway.

**Comment by JagandeepBrar** [comment]
If you long hold the red <!> icon on either the search list or on the details page, it will show a prompt asking if you still want to download the release.

I will separate it into two FABs though to stop the confusion in future releases, but it is currently implemented.

**Comment by JagandeepBrar** [comment]
I have now separated it into two different FABs. Will be added into the next release, or you can build from source now.

![IMG_0626](https://user-images.githubusercontent.com/3048295/71733858-2dbdf680-2e10-11ea-8001-357c8f2589aa.png)
