### ISSUE TITLE
[Feature Request] Custom manual search string

### ISSUE THREAD

**Issue by elmstreetvictim** [JagandeepBrar/LunaSea#31]
When manual searching i would like to specify my own string. Even though it might return results that are not even in the ballpark. Say I have “Best Picture 2019” in my wanted list, and instead of searching “Best Picture 2019 full movie hd megaupload”, I search for “baseball comic books”. I don’t want LunaSea to care that these two things aren’t the same. I would just like the flexibility to type in something else like “Best Picture hive-cm8” and then decide for myself whether the results are useful. 

(There are certain items on indexers that don’t appear within the -arr applications thru their search interfaces, but turn up in a manual search on the indexer site)

**Comment by JagandeepBrar** [comment]
The string in that search bar has no impact on the searches, it's just a small joke for those that remember downloading videos from megaupload a while back. It currently uses whatever service's built in search engine. The ability to manually search indexers and download releases is planned for the future.

**Comment by JagandeepBrar** [comment]
Just going to close this issue in favour of #40 which is requesting the same thing!
