### ISSUE TITLE
[Bug] search results have the text label truncated 

### ISSUE THREAD

**Issue by elmstreetvictim** [JagandeepBrar/LunaSea#32]
Within manual search results the file names are cut off because there is no multi-line or word wrap. Even when following to the detail page sometimes the file name is not completely visible. 

Best.Picture.2019.1080p.DTS.BluRay.x264-SCeNe.mkv 

Can this be changed to wrap somewhere within the string, maybe at a period or hyphen?

**Comment by JagandeepBrar** [comment]
When viewing the details of a release, if you tap on the "Release Title" card it will show a prompt with the full title of the release.
