### ISSUE TITLE
[Feature Request] Sorting Options

### ISSUE THREAD

**Issue by Lasikie** [JagandeepBrar/LunaSea#4]
Could the ability to sort lists please be added?

Next aired, release date, etc

**Comment by JagandeepBrar** [comment]
There are some types of sorting that wouldn’t be possible without fetching a huge amount of data on the initial refresh, but I can take a look into the options that are available and try to implement some!

**Comment by JagandeepBrar** [comment]
Some basic sorting options will be included in the next release, with more complex ones coming in the future.

**Comment by simonk83** [comment]
Yep came here to request this also. For Radar/Sonarr my preference is to have it sorted by release date so I can quickly see what’s coming up next, if that options is possible?

**Comment by JagandeepBrar** [comment]
This has now been implemented, in `v1.0.0` branch and will come in the next release! All 3 -rr services now have the ability to sort, via a button beside the search bar.

More sorting options might come in the future, but these seem like the two major ones to care about for now.

![IMG_0756](https://user-images.githubusercontent.com/3048295/73488801-3520e300-436f-11ea-8f67-e91d3bc03434.png)

**Comment by simonk83** [comment]
Would Date Added be a possibility?

**Comment by JagandeepBrar** [comment]
> Would Date Added be a possibility?

@simonk83 Date added to Sonarr (or whatever service)? That should be possible, I was going to add Date Added, Last Aired, and Next Airing as options probably.

**Comment by simonk83** [comment]
Awesome, all three of those would be great 👍🏻
