### ISSUE TITLE
[Feature Request]  Support for Indexers

### ISSUE THREAD

**Issue by theg00s3** [JagandeepBrar/LunaSea#40]
**Describe the solution you'd like**
The ability to search NZBHydra for files and send them to SABnzbd/NZBGet

**Comment by JagandeepBrar** [comment]
Sorry for taking a few days to respond, just got really sick over the weekend...

I am currently implementing a logging system (should be done very soon), then next is going to NZBGet. After that is when I will start implementing indexer searching (including NZBHydra).

**Comment by sittingmongoose** [comment]
Just wanted to comment and say I would love this feature!

**Comment by JagandeepBrar** [comment]
Just as an update, this has been almost entirely implemented and will be live in a TestFlight release this weekend (hopefully!)

Just custom searching UI remains, but it's been implemented at an API level so it shouldn't take long.

**Comment by JagandeepBrar** [comment]
This is now live in TestFlight v2.0.0 (33)!
