### ISSUE TITLE
[Bug] Webhook notifications do not work on devices without Google Play Services

### ISSUE THREAD

**Issue by ethanmlee** [JagandeepBrar/LunaSea#470]
**Describe the Bug**
webhook not copying to clipboard on android device (android 10) when tapping the device button on any of the services present on the Notification settings page

**To Reproduce**
Open LunaSea v5.0.0 (50000019) on android 10 device go to Settings > Notifications > tap "device" under Lidarr, Overseerr, Radarr, Sonarr, or Tuatulli.

**Expected Behaviour**
the webhook url to be copied to the clipboard when tapping device

**Versions**
LunaSea v5.0.0 (50000019)

**Comment by JagandeepBrar** [comment]
Can you let me know which device you are using?

I am running Android 11 on a Pixel 3, have no issues copying the webhook URLs.

**Comment by shammyfiveducks** [comment]
Same issue for V5.1- Webhooks URL will not copy to clipboard.

I have a Huawei P40 phone - is it something to do with the lack of Google Services maybe?

**Comment by ethanmlee** [comment]
> 
> 
> Same issue for V5.1- Webhooks URL will not copy to clipboard.
> 
> I have a Huawei P40 phone - is it something to do with the lack of Google Services maybe?

i didn't think about google play services. I have a oneplus 5t running crdroid with microg. that is probably what the issue is tbqh.

**Comment by JagandeepBrar** [comment]
> Same issue for V5.1- Webhooks URL will not copy to clipboard.
> 
> I have a Huawei P40 phone - is it something to do with the lack of Google Services maybe?

Ah, yes. LunaSea's notification backend relies on Firebase, which in turn relies on Google Services. I will add checks within LunaSea to hide the notification section for users without Firebase support, but for the time being notifications (and any user account features) will not be compatible with devices without Google Services.
