### ISSUE TITLE
[Feature Request] Support qBittorrent

### ISSUE THREAD

**Issue by luisvillalobos528** [JagandeepBrar/LunaSea#49]
**Describe the solution you'd like**
Support torrent client, qBittorrent.

https://www.qbittorrent.org/

**Comment by JagandeepBrar** [comment]
Hi!

Torrent support is definitely in the pipeline, but for the time being the focus is to get usenet support up to spec, with support for the most popular clients:

- SABnzbd (Implemented)
- NZBGet (Next release)

Then I will be implementing support for direct indexer search, but will likely do NZBHydra for the time being as it's a community favourite and support individual indexers later in the pipeline.

After these have been implemented, next on the list is definitely torrent clients, then monitoring agents such as Tautulli, Plex, etc.

**Comment by sittingmongoose** [comment]
Just wanted to comment and say I would love this feature!

**Comment by JagandeepBrar** [comment]
Folding all of the torrent client requests into one issue.

https://github.com/JagandeepBrar/LunaSea/issues/90
