### ISSUE TITLE
[Feature Request] IMDB link to App

### ISSUE THREAD

**Issue by luisvillalobos528** [JagandeepBrar/LunaSea#51]
**Describe the solution you'd like**
Hi, I just noticed that when you click the IMDB icon on the overview page of a show or movie it opens a in-app safari windows to imdb, I have the IMDB app installed it would be better or cooler in my opinion that if you got the IMDB app installed it will open the app instead of the safari page.

Don't know if that is possible

Again superb work on everything.

**Comment by JagandeepBrar** [comment]
This is definitely doable, I’ll implement it for the next release for all external links that have an app available and support linking (YouTube, IMDb, Discogs(?))

**Comment by JagandeepBrar** [comment]
An update for this has been merged into `master`, and will be included in the next release.
