### ISSUE TITLE
[Feature Request] Support for Deluge

### ISSUE THREAD

**Issue by staticn0de** [JagandeepBrar/LunaSea#55]
**Describe the solution you'd like**
Support for the torrent client, Deluge.

**Comment by JagandeepBrar** [comment]
Will be added in the future once usenet services have been implemented, alongside other torrent clients.

**Comment by JagandeepBrar** [comment]
Folding all of the torrent client requests into one issue.

https://github.com/JagandeepBrar/LunaSea/issues/90
