### ISSUE TITLE
[Bug] Does not support 120Hz Displays

### ISSUE THREAD

**Issue by serialtoon** [JagandeepBrar/LunaSea#551]
**Describe the Bug**
Nothing specific outside of the scrolling behavior on iOS is very studdery/jank

**To Reproduce**
Just scroll around the various pages and lists in your catalogs. 

**Expected Behaviour**
Prior to V6, scrolling behavior was smooth as it should be, especially on iOS 15 with iPhone 13 Pro Max (120hz)

**Screenshots**

**Versions**
v6.0
**Additional context**
Device: iPhone 13 Pro Max
iOS: 15.2

**Comment by JagandeepBrar** [comment]
Can you show me a video example of this occurring? I have the same device (iPhone 13 Pro Max, iOS 15.2) and I see normal performance.

LunaSea does not currently run at 120Hz if that is what you mean, it never has. Flutter, the framework, has to add support for 120Hz which I am waiting on: https://github.com/flutter/flutter/issues/90675

**Comment by serialtoon** [comment]
> Can you show me a video example of this occurring? I have the same device (iPhone 13 Pro Max, iOS 15.2) and I see normal performance.
> 
> LunaSea does not currently run at 120Hz if that is what you mean, it never has. Flutter, the framework, has to add support for 120Hz which I am waiting on: [flutter/flutter#90675](https://github.com/flutter/flutter/issues/90675)

The link you provided pretty much describes exactly what im experiencing. I did a screen cap however i dont think its translating the same as when i see it appear on my display. Unless iOS is doing some fuckery with the video playback on the native photos app.

**Comment by JagandeepBrar** [comment]
[LunaSea v10.0.3](https://github.com/JagandeepBrar/LunaSea/releases/tag/v10.0.3) is released which is built using Flutter 3 and supports ProMotion displays!

The update is still in review with the App Store but should be released within the next day.

**Comment by serialtoon** [comment]
Excellent news!! Thank you!
