### ISSUE TITLE
[Feature Request] Search bar improvement

### ISSUE THREAD

**Issue by luisvillalobos528** [JagandeepBrar/LunaSea#59]
**Describe the solution you'd like**
When you go to radarr in the search tab and onto the search bar lets say you write the following text: Avatar and hit enter, the search doesn't start until you then hit the search icon the green one, would be nice if it after you write the movie name and hit enter on the keyboard it triggers the search.

**Comment by JagandeepBrar** [comment]
This will be added in the next release (v0.4.0+1).
