### ISSUE TITLE
Request - Summary info into Quick Access links

### ISSUE THREAD

**Issue by bktz** [JagandeepBrar/LunaSea#6]
Hello,

Thanks for all the amazing work! I have a request for the home screen. Currently the home screen has quick access icons to take you to an automation with a summary of the automations below. Would it be possible to make the summary a button that would link to the automation similar to the quick access icons above? With the data and label already on the screen it would be nice if we could interact with it rather than just having it be static text.

Thanks!

**Comment by JagandeepBrar** [comment]
Already implemented in a future release!

**Comment by JagandeepBrar** [comment]
Fixed in the just released v0.3.0+1.
