### ISSUE TITLE
[Other] respect screen rotation when viewing externals

### ISSUE THREAD

**Issue by gingerbeardman** [JagandeepBrar/LunaSea#616]
I use some external modules that aren't mobile optimized. They look a bit better when using the phone rotated to landscape orientation. 

But LunaSea keeps everything in portrait mode and doesn't respect the rotation of my device screen. 

Please add the ability to show the screen in landscape when viewing externals. 

LunaSea
![image](https://user-images.githubusercontent.com/49612/152976027-976eddfd-98b5-4b07-9135-06ff97e43c60.png)

Safari
![image](https://user-images.githubusercontent.com/49612/152976059-c51f8f5c-4ae2-4d97-9ff6-2ac5657e5961.png)

**Comment by JagandeepBrar** [comment]
Rotation is now supported on all platforms and that should include external modules in integrated WebViews!

**Comment by gingerbeardman** [comment]
Awesome - thanks!
