### ISSUE TITLE
[Other] Release naming convention

### ISSUE THREAD

**Issue by xrths** [JagandeepBrar/LunaSea#638]
Hello,

Can you keep the same syntax when you publish a release? 
Otherwise it complicates the updates on Homebrew.

_The format: v{version}/LunaSea-macOS.zip is fine._

Example: 
**Current version :**
https://github.com/JagandeepBrar/LunaSea/releases/download/**v10.0.0**/**LunaSea-macOS**.zip

**Previous version :** 
https://github.com/JagandeepBrar/LunaSea/releases/download/**6.0.0%2B60000006**/**LunaSea-macOS-60000006**.zip

**Comment by JagandeepBrar** [comment]
From now on, the release convention will stay as the most recently release:

> LunaSea-macOS.zip

It was changed because of recent changes to the CI/CD pipeline, but won't be changing from now on.

**Comment by xrths** [comment]
Perfect. Thank you.
