### ISSUE TITLE
[Feature Request]Support for multiple Sonarr and Radarr instances

### ISSUE THREAD

**Issue by sittingmongoose** [JagandeepBrar/LunaSea#65]
With 4K being such a big thing now, the only real way to manage it in Plex or Emby is to have separate folders for 4K and additional copies.  Being able to check my other instances would be amazing.  Currently I need to keep 4 tabs open on my phone to accommodate this.

**Comment by JagandeepBrar** [comment]
This is the intended use case of the "Profiles" feature.

You can create another profile, and add the details for another instance of Radarr/Sonarr/etc into that. You can then switch between the two profiles to switch between multiple instances.

Currently there is no easy way to quickly switch (you must go into Settings and set the enabled profile), but I have the intention of adding it into the drawer header.
