### ISSUE TITLE
[Feature Request] Ability to see if you already have a movie or show in Sonarr or Radarr when you're searching for new ones

### ISSUE THREAD

**Issue by sittingmongoose** [JagandeepBrar/LunaSea#66]
**Describe the solution you'd like**
It would be really nice to search a movie on radarr and see if its already in your library instead of just getting an error after to click add.  Similar to have Sonarr and Radarr currently look.

**Comment by JagandeepBrar** [comment]
Added in #95, available in the `v1.0.0` branch now or you can wait for the next release.
