### ISSUE TITLE
[Bug] Unable to connect to any of my resources with the web.lunasea.app

### ISSUE THREAD

**Issue by Syberiyxx** [JagandeepBrar/LunaSea#661]
**Describe the Bug**
Error and failure when trying to connect to any of my resources with web.lunasea.app.

**To Reproduce**

1. Open site
2. login to account
3. restore backup from known working device
4. Press "Test Configuration" for Tautulli (Radarr, Sonarr) from restored backup
5. (My server is setup using http and a subdomain)

**Expected Behaviour**
successful connection, services to appear and function normally

**Actual Behaviour**
When in Firefox:

> `DioError [DioErrorType.response]: XMLHttpRequest error.
> Source stack:
> DP@https://web.lunasea.app/main.dart.js:4963:24
> aSg/$async$nQ<@https://web.lunasea.app/main.dart.js:62797:5
> c/s@https://web.lunasea.app/main.dart.js:3627:63
> $2@https://web.lunasea.app/main.dart.js:55396:14
> f@https://web.lunasea.app/main.dart.js:3613:10
> aSg@https://web.lunasea.app/main.dart.js:62814:10
> nQ@https://web.lunasea.app/main.dart.js:62792:23
> aZN/$async$w7<@https://web.lunasea.app/main.dart.js:62787:5
> c/s@https://web.lunasea.app/main.dart.js:3627:63
> $2@https://web.lunasea.app/main.dart.js:55396:14
> f@https://web.lunasea.app/main.dart.js:3613:10
> aZN@https://web.lunasea.app/main.dart.js:62791:10
> w7@https://web.lunasea.app/main.dart.js:62778:35
> aZM@https://web.lunasea.app/main.dart.js:62779:32
> aZ@https://web.lunasea.app/main.dart.js:62769:25
> e7@https://web.lunasea.app/main.dart.js:62770:23
> bWW/$async$bWW<@https://web.lunasea.app/main.dart.js:30096:14
> c/s@https://web.lunasea.app/main.dart.js:3627:63
> $2@https://web.lunasea.app/main.dart.js:55396:14
> f@https://web.lunasea.app/main.dart.js:3613:10
> bWW@https://web.lunasea.app/main.dart.js:30103:10
> Co/$async$Co<@https://web.lunasea.app/main.dart.js:117921:33
> c/s@https://web.lunasea.app/main.dart.js:3627:63
> $2@https://web.lunasea.app/main.dart.js:55396:14
> f@https://web.lunasea.app/main.dart.js:3613:10
> Co@https://web.lunasea.app/main.dart.js:117925:10
> $0/$async$$0<@https://web.lunasea.app/main.dart.js:130463:42
> c/s@https://web.lunasea.app/main.dart.js:3627:63
> $2@https://web.lunasea.app/main.dart.js:55396:14
> f@https://web.lunasea.app/main.dart.js:3613:10
> $0@https://web.lunasea.app/main.dart.js:130465:10
> $0/$async$$0<@https://web.lunasea.app/main.dart.js:108417:26
> c/s@https://web.lunasea.app/main.dart.js:3627:63
> $2@https://web.lunasea.app/main.dart.js:55396:14
> f@https://web.lunasea.app/main.dart.js:3613:10
> $0@https://web.lunasea.app/main.dart.js:108419:10
> a_3@https://web.lunasea.app/main.dart.js:72520:14
> ctR/<@https://web.lunasea.app/main.dart.js:2555:79
> a6I@https://web.lunasea.app/main.dart.js:70000:9
> hk@https://web.lunasea.app/main.dart.js:70004:21
> a64@https://web.lunasea.app/main.dart.js:70158:14
> XZ@https://web.lunasea.app/main.dart.js:70131:3
> jP@https://web.lunasea.app/main.dart.js:70113:3
> X6@https://web.lunasea.app/main.dart.js:69056:29
> kK@https://web.lunasea.app/main.dart.js:69129:25
> RS@https://web.lunasea.app/main.dart.js:69121:14
> RS@https://web.lunasea.app/main.dart.js:91585:6
> a_0@https://web.lunasea.app/main.dart.js:69112:36
> aUp@https://web.lunasea.app/main.dart.js:69103:6
> Np@https://web.lunasea.app/main.dart.js:69101:41
> awN@https://web.lunasea.app/main.dart.js:69097:19
> ctR/<@https://web.lunasea.app/main.dart.js:2556:65
> aAM@https://web.lunasea.app/main.dart.js:517:15
> aBo@https://web.lunasea.app/main.dart.js:51007:3
> ctR/<@https://web.lunasea.app/main.dart.js:2556:65
> $1@https://web.lunasea.app/main.dart.js:51172:5
> $1@https://web.lunasea.app/main.dart.js:51142:21
> $1@https://web.lunasea.app/main.dart.js:51019:42
> cLm@https://web.lunasea.app/main.dart.js:2515:17
> mh/s@https://web.lunasea.app/main.dart.js:2523:51
> `

When in Vivaldi

> `DioError [DioErrorType.response]: XMLHttpRequest error.
> Source stack:
> Error
>     at Object.DP (https://web.lunasea.app/main.dart.js:4963:24)
>     at https://web.lunasea.app/main.dart.js:62797:5
>     at bYu.a (https://web.lunasea.app/main.dart.js:3627:62)
>     at bYu.$2 (https://web.lunasea.app/main.dart.js:55396:14)
>     at Object.f (https://web.lunasea.app/main.dart.js:3613:10)
>     at aH2.aSg (https://web.lunasea.app/main.dart.js:62814:10)
>     at aH2.nQ (https://web.lunasea.app/main.dart.js:62792:23)
>     at https://web.lunasea.app/main.dart.js:62787:5
>     at bYu.a (https://web.lunasea.app/main.dart.js:3627:62)
>     at bYu.$2 (https://web.lunasea.app/main.dart.js:55396:14)`
> 

When in Brave

> `DioError [DioErrorType.response]: XMLHttpRequest error.
> Source stack:
> Error
>     at Object.DP (https://web.lunasea.app/main.dart.js:4963:24)
>     at https://web.lunasea.app/main.dart.js:62797:5
>     at bYu.a (https://web.lunasea.app/main.dart.js:3627:62)
>     at bYu.$2 (https://web.lunasea.app/main.dart.js:55396:14)
>     at Object.f (https://web.lunasea.app/main.dart.js:3613:10)
>     at aH2.aSg (https://web.lunasea.app/main.dart.js:62814:10)
>     at aH2.nQ (https://web.lunasea.app/main.dart.js:62792:23)
>     at https://web.lunasea.app/main.dart.js:62787:5
>     at bYu.a (https://web.lunasea.app/main.dart.js:3627:62)
>     at bYu.$2 (https://web.lunasea.app/main.dart.js:55396:14)`

My server is setup using http and a subdomain

**Screenshots**
![image](https://user-images.githubusercontent.com/2048087/163594401-8a976e15-446e-4200-88ef-8c2e8e0556b0.png)

**Versions**
web.lunasea.app v10.0.2

running on

Linux Pop!_OS 21
Brave 1.39.113
Vivaldi 5.2.2623.36 (Stable channel) stable (64-bit) 
Firefox 99.0

**Comment by JagandeepBrar** [comment]
> "My server is setup using http and a subdomain"

The modules must be exposed via HTTPS to be compatible with LunaSea Web, as [described here](https://docs.lunasea.app/getting-started/platform-restrictions#https-requirement).

In the near future Docker images will be available where you can host your own copy of LunaSea Web which could then be exposed via HTTP and be able to connect to resources exposed via HTTP.
