### ISSUE TITLE
[Feature Request] Add support for multiple Sonarr and Radarr releases

### ISSUE THREAD

**Issue by sittingmongoose** [JagandeepBrar/LunaSea#67]
With 4K being such a big thing now, the only real way to manage it in Plex or Emby is to have separate folders for 4K and additional copies. Being able to check my other instances would be amazing. Currently I need to keep 4 tabs open on my phone to accommodate this.

**Comment by sittingmongoose** [comment]
I saw your response before I closed it.  Using profiles to switch between 1080p and 4K is nifty.  Ill try that out.  Thank you

**Comment by JagandeepBrar** [comment]
Hope that solution works for you! Going to close this issue as well if that's okay, if there is something else you can reopen it/open another.
