### ISSUE TITLE
[Bug] <Calendar from Dashboard Broken>

### ISSUE THREAD

**Issue by erikt311** [JagandeepBrar/LunaSea#675]
**Describe the Bug**
The calendars within Lidarr, Sonarr, etc work fine individually, but the (I assume) consolidate calendar on the dashboard doesn't. 

**To Reproduce**
Self explanatory, but see video. 

**Expected Behaviour**
The calendar opens :)

**Screenshots**
https://user-images.githubusercontent.com/54078801/169857348-1ad9b936-06f6-4fa3-8238-f7da9ad904e1.MOV

**Versions**
10.0.2
iOS 15.4.1
IPhone SE A2275

**Additional context**

**Comment by JagandeepBrar** [comment]
Can you see what is recorded within the logs when this occurs?

**Comment by erikt311** [comment]
Oddly, when I tried the unified calendar just now, it worked fine...so I don't know!

**Comment by JagandeepBrar** [comment]
Thanks @erikt311, it looks to be a transient database issue (the log shows it wasn't able to pull your host from the database when constructing the URL). It appears to have fixed itself somehow but if you run into the same problem please re-open the issue and I can continue to investigate.
