### ISSUE TITLE
[Bug] Tapping on the iPhone notifications gets the message Unknown Profile.

### ISSUE THREAD

**Issue by romeolazar** [JagandeepBrar/LunaSea#681]
**Describe the Bug**
I use webhooks to get notified. They are working but when I tap on the notification on iPhone I get the message:
Unknown Profile
"default" does not exists in LunaSea

**To Reproduce**
not sure.
**Expected Behaviour**
Should take me to the episode/movied that was downloaded.

**Screenshots**
![IMG_3297](https://user-images.githubusercontent.com/78906276/172310216-66354c85-faf5-410b-8537-78ca61b3eed4.PNG).

**Versions**
10.0.3/iOS/Stable/Build 
1000000773(89241c7)

**Additional context**

**Comment by JagandeepBrar** [comment]
Hey @romeolazar,

Ensure that you have correctly set your profile's name in the webhook. Check the "Username" tab in the instructions here for more details: https://docs.lunasea.app/notifications/sonarr#setup-the-webhook

**Comment by romeolazar** [comment]
Thank you very much for the indications, helped me to solve it. Was not clear to me that I had to insert the profile name.
Great job with this app. Keep up with the good work.
