### ISSUE TITLE
[Feature Request] Add Upcoming tab to Radarr

### ISSUE THREAD

**Issue by simonk83** [JagandeepBrar/LunaSea#70]
You have it working for Sonarr which is great, but would be awesome to have it for Radarr as well to quickly see what’s coming up at a glance. 

Thanks!

**Comment by JagandeepBrar** [comment]
The missing tab in Radarr kind of serves as a mix of missing titles and upcoming titles. 

The titles with the red "Release xx Days Ago" are titles missing from your library, the blue "Available in xx Days" are the ones currently in cinema and will be available on physical media soon, and orange "In Cinemas in xx Days" are titles that have not even hit the cinemas yet.

**Comment by simonk83** [comment]
Yep I hear you, but I guess it’s just a little odd from a design perspective, as Sonarr also has a Missing tab as well as Upcoming so it’s sort of expected to see in both. 
It would help a bit if the Radarr Missing tab was sortable though (and it remembered the sort setting) so you could choose to have the upcoming releases shown first. The Missing functionality in both Sonarr and Radarr is something I basically never ever check to be honest, as I generally know if I’m missing an episode, and the stuff shown in there is almost always “you already have this but not at the quality you requested”, so it’s just clutter.
