### ISSUE TITLE
Can't enable overseerr notifications since changing phone 'no devices found'

### ISSUE THREAD

**Issue by neoestremi** [JagandeepBrar/LunaSea#721]
### Discussed in https://github.com/JagandeepBrar/LunaSea/discussions/720

<div type='discussions-op-text'>

<sup>Originally posted by **neoestremi** October 25, 2022</sup>
Hi,
I had a new phone recently and had tried to get the notifications working but without success (everything worked fine before).
I tried to reinstall, delete and recreate an account, restart overseerr, restart the whole server but nothing seems to fix it, I still have the same message in my logs :
`[Notifications]: Error sending LunaSea notification {"type":"TEST_NOTIFICATION","subject":"Test Notification","errorMessage":"Request failed with status code 400","response":{"message":"No Devices Found"}}`
The webhook I'm using is the user one, since device link doesn't seem to be generated when clicking.
Overseerr 1.30.1
Lunasea 10.2.0</div>

**Comment by neoestremi** [comment]
Update : tested it with radarr, same issue, error 400 : no devices found

**Comment by JagandeepBrar** [comment]
We were able to resolve the issue by discovering that you must whitelist the following domains in any DNS sinkholes/proxies:

1. `https://firebaseinstallations.googleapis.com`
2. `https://device-provisioning.googleapis.com`
