### ISSUE TITLE
[Bug] Notifications deeplinks error when the profile name changes. 

### ISSUE THREAD

**Issue by timrettop** [JagandeepBrar/LunaSea#729]
**Describe the Bug**
While creating a new profile, I also renamed the existing profile that was named default to "Main".  Since then, clicking on notifications takes me to the app with a message "Unknown Profile" ... "default" does not exist in LunaSea. 

**To Reproduce**
1. Setup user notification on a service, e.g. Sonarr without changing profile name ("default"). 
2. Change profile name
3. Wait for notification and click on it. 

**Expected Behaviour**
Changes to the profile name should be handled by the notification system. 

**Screenshots**
![IMG_605E65C54C0C-1](https://user-images.githubusercontent.com/434913/204197429-43c94953-e3fa-4cf2-8866-7a8ff26ab0a8.jpeg)

**Versions**
10.2.2 (Edge) build hash c46924c

**Additional context**
Changing the name back to default returns to expected behavior.

**Comment by JigSawFr** [comment]
Facing the same problem (iOS)

**Comment by JagandeepBrar** [comment]
Hi @timrettop, @JigSawFr, did you both go through the process of correctly setting the profile in the webhook configuration?

In [Sonarr's notification documentation](https://docs.lunasea.app/notifications/sonarr#setup-the-webhook) for example, please click the "Username" tab to further understand what I mean.

If this does not resolve the issue, please re-open the issue but off my testing it seems to be working as expected.

**Comment by timrettop** [comment]
Yes thats right, that addresses my issue, thank you! 

Maybe alternatively there should be a warning triggered if the default profile name is changed or a new profile is added to check the notification webhooks?
