### ISSUE TITLE
[Bug] Swiping between pages does not function on iOS

### ISSUE THREAD

**Issue by PixelMelt** [JagandeepBrar/LunaSea#734]
**Describe the Bug**
N/A

**Versions**
v10.2.2 iOS build

**Additional context**
Swiping does work on iOS build v10.2.1

**Comment by JagandeepBrar** [comment]
This is an intended change and was noted in the changelog as a desired UX change.

https://github.com/JagandeepBrar/LunaSea/commit/968fe9cbbc4aff3ae584682e462defbf09ea5699
