### ISSUE TITLE
[Bug] Cover & poster fail to load if add new movie to radarr through LunaSea

### ISSUE THREAD

**Issue by flymin** [JagandeepBrar/LunaSea#736]
**Describe the Bug**
Add a new movie to radarr through LunaSea. The cover and poster cannot load.

**To Reproduce**
In the LunaSea radarr panel, click "+" on upper-right and add a movie. The cover and poster cannot load even after restarting app / clearing the cache / disabling the profile and enabling again.

**Expected Behaviour**
The cover and poster should display.

**Screenshots**
<img width="414" alt="image" src="https://user-images.githubusercontent.com/28671430/211720191-130809db-4f6e-44eb-ba10-9d8b4a383c44.png">

**Versions**
LunaSea v10.2.2 on IOS
Radarr v4.3.2.6857

**Additional context**
I checked the MediaCover folder of radarr. The fanart and poster exist normally. I tried to add the same item from radarr website and then refresh LunaSea. The cover and poster can display normally.

**Comment by matjako** [comment]
Bug still present in LunaSea v10.2.3 (macOS and iOS) and Radarr v4.4.2.6956. I am attaching the log file:

`        "timestamp": "2023-03-02T13:12:11.466",
        "type": "Critical",
        "message": "HttpException: Invalid statusCode: 404, uri = https://radarr.XXX.XXX/api/v3/MediaCover/214/poster-500.jpg?apikey=XXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "error": "HttpException: Invalid statusCode: 404, uri = https://radarr.XXX.XXX/api/v3/MediaCover/214/poster-500.jpg?apikey=XXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
`

**Comment by JagandeepBrar** [comment]
The issue here is that Radarr adds the movie then internally fetches metadata including images. Sometimes LunaSea has already attempted to fetch the image which was not found because it hasn't been fetched by Radarr yet, which is the reason for the media covers not being present sometimes on newly added content.

I will however look into why the HTTP request is being cached and not attempting a reload, especially after an image cache clear.

**Comment by JagandeepBrar** [comment]
I have implemented a new technique that uses a new backend package for caching and persitence of network images, including a built-in retry operation.

I was able to test and confirm the functionality of the clearing of persisted images using this new implementation. This new implementation will also ensure that any images that failed-to-load will attempt a re-fetch on a widget rebuild.

I am hopeful that this resolves this issue so I will be closing it for now. I will update here again once the update is live in stable for further testing and we can re-open the issue if it still persists.

https://github.com/JagandeepBrar/LunaSea/commit/11d0b9cd7348c740025b13957466a43c3f429a45

**Comment by JagandeepBrar** [comment]
I have polished the current implementation to also clear in-memory images and not just persisted images when clearing via the settings. This should hopefully resolve the issue on newly fetched images which may not have loaded correctly. Please test in the next stable release and re-open the issue if the problem still occurs.
