### ISSUE TITLE
[Feature Request] Remove the megaupload dialog?

### ISSUE THREAD

**Issue by simonk83** [JagandeepBrar/LunaSea#74]
![E0D09E50-C1EB-4424-B108-7EBD4438D7B3](https://user-images.githubusercontent.com/518440/73206223-a8233180-4196-11ea-82ff-5eec4db8ca3a.jpeg)

Whenever you go to search for something it seems to auto populate the name of the movie along with “full movie HD megaupload”, but it seems to serve no purpose. It’s a bit confusing to be honest as it’s not a part of Radarr functionality as far as I know, clicking it doesn’t actually do anything, and the text isn’t editable. It makes you think it’s going to try and search for that somehow, when the real functionality is in the Automatic and Manual search buttons below it.

**Comment by JagandeepBrar** [comment]
Yeah, I should probably remove this. I added it as a little joke at first, but it seems to be adversely causing confusion, will be removed with the next release.

**Comment by JagandeepBrar** [comment]
Changes have been merged into the branch `v0.4.1+1` and will be in the next release!
