### ISSUE TITLE
[Other] Are the translations availables ?

### ISSUE THREAD

**Issue by rhayart** [JagandeepBrar/LunaSea#741]
Hi,

I Just discover LunaSea, and saw a translation field in the app settings.
Also there is a Weblate platform for translation with some languages already filled at 100%.
I also saw some merges of the Weblate translations.

But i can't choose an other language in the app.
Is this an issue ?
If not why the translations that are ready are not integrated ?

Thanks in advance for your time !

**Comment by JagandeepBrar** [comment]
LunaSea hasn't had all the strings inside the app prepared for localization as it has been a retrofit initiative. Because of this, I didn't want to enable it in stable releases but if you download either beta or edge releases you can access the localized languages.
