### ISSUE TITLE
[Bug] External Modules open in Safari

### ISSUE THREAD

**Issue by gingerbeardman** [JagandeepBrar/LunaSea#742]
**Describe the Bug**
In the latest TestFlight build, released today, choosing an External Module opens it in Safari rather than in the app. 

**To Reproduce**
- use latest TestFlight build
- tap an external module

**Expected Behaviour**
- should open in the app

**Versions**
- 10.2.3

**Notes**
- 10.2.2 doesn't have the problem

**Comment by JagandeepBrar** [comment]
Thanks for catching this, fixed in https://github.com/JagandeepBrar/LunaSea/commit/596eab4bad1aa183e3c0dfc8d20a32c15ecdb78d!

**Comment by gingerbeardman** [comment]
Any chance this will hit TestFlight?

I'm back on App Store version 10.2.2

**Comment by JagandeepBrar** [comment]
@gingerbeardman The TestFlight builds are actually building right now, Edge and Beta releases are out and the Candidate release should be live within the next hour. 10.2.3 will be released to stable in the next day or two as well, in case you wanted to stay on the stable releases.

**Comment by gingerbeardman** [comment]
Thanks!
