### ISSUE TITLE
[Bug] Image Missing from Tautulli Recently Added Notification Android

### ISSUE THREAD

**Issue by esmoyer** [JagandeepBrar/LunaSea#743]
**Describe the Bug**
When receiving a notification via Tautulli it shows the show and episode title but the image included is a grey Plex image

**To Reproduce**
Setup Tautulli in LunaSea, download new show or episode and receive notification 

**Expected Behaviour**
Episode or Show image show along with the text info

**Screenshots**
![Screenshot_20230323-203331](https://user-images.githubusercontent.com/17444085/227403281-f37bef6e-b2eb-4540-9b7f-5f5378b6c511.png)

**Versions**
Lunasea 10.2.3
Tautulli 2.12.2

**Additional context**
Not sure if that is what is supposed to show or not. Was trying to see if maybe something was blocked or i was missing a setting, but couldn't figure it out.

**Comment by JagandeepBrar** [comment]
Please follow the instructions to attach images to Tautulli notifications: https://docs.lunasea.app/lunasea/notifications/tautulli#attach-images-to-notifications

**Comment by esmoyer** [comment]
Oh wow...I swear I looked over the docs but completely missed it; looking back I was looking this page: https://docs.lunasea.app/modules/tautulli Thank you!
