### ISSUE TITLE
[Feature Request] Implement the "pause for..." feature of Nzbget

### ISSUE THREAD

**Issue by simonk83** [JagandeepBrar/LunaSea#76]
Similar to issue #75 , the "pause for 5, 10, 30 mins etc" feature is handy to have in case you want to temporarily pause things, but have it auto resume after a while (I tend to forget about it otherwise).

**Comment by JagandeepBrar** [comment]
I will add this functionality for the next release!

**Comment by simonk83** [comment]
Awesome, thanks mate. Thinking about it more, could maybe just have these options pop up if you hold down the existing pause button (long hold).

**Comment by JagandeepBrar** [comment]
Been implemented in branch `v1.0.0`, will be live in the next release and next TestFlight beta!

You hold down on the pause/resume floating action button to get a prompt for how long you would like to pause for.

![IMG_0761](https://user-images.githubusercontent.com/3048295/73567933-ffdaca80-442c-11ea-9103-1b7a1b33c78b.png)
