### ISSUE TITLE
[Bug] NZBGet Displays Grey Screen

### ISSUE THREAD

**Issue by simonk83** [JagandeepBrar/LunaSea#77]
**Describe the Bug**
![A0052A68-C3FF-4824-8B67-B6C00ED66E7D](https://user-images.githubusercontent.com/518440/73230587-e7bb3f00-41d1-11ea-96ba-3b96604a8e3d.png)

Opening Nzbget now just shows this grey screen. I’ve tried closing and reopening. The logs are showing:

![9A308E4D-DC4E-4786-8614-271C3BD79993](https://user-images.githubusercontent.com/518440/73230644-1fc28200-41d2-11ea-96f6-3f000b1def06.jpeg)

**To Reproduce**
I think this may have happened after I chose the “Unlimited” option in the Speed Limit section.

**Comment by simonk83** [comment]
Ok, this now appears to have come good (it’s loading again). Nzbget was repairing an entire season of a show at the time, and when that finished the UI started loading again. Not too sure how that correlates with the speed limit setting though, unless it was queuing that command and it didn’t properly go through until the repair was finished, or something like that.

**Comment by JagandeepBrar** [comment]
Thanks for this, I'll take a look into it. Definitely has to do with the repairing and not the speed limit, since that wouldn't directly effect the UI.

**Comment by JagandeepBrar** [comment]
This has been fixed in 0345e8a, and is available in the branch `v1.0.0`.

Fix will be in included in the next release.
