### ISSUE TITLE
[Other] macOS TestFlight build expired

### ISSUE THREAD

**Issue by aniqueta** [JagandeepBrar/lunasea#770]
Is it possible to get this pushed to TestFlight again or ideally to the Mac App Store? Thanks.

**Comment by JagandeepBrar** [comment]
Apologies for this, new builds up-to stable have been submitted to the App Store and should be live once they have passed the review process.

I am thinking of publishing the macOS application in the near future to the App Store but at this time will be sticking with TestFlight.

**Comment by aniqueta** [comment]
@JagandeepBrar Happy New Year. Looks like the TestFlight build expired again. Would be great to get this on the macOS App Store this year. Thanks!
