### ISSUE TITLE
[Bug] <Put Your Title Here>

### ISSUE THREAD

**Issue by edrock200** [JagandeepBrar/lunasea#775]
**Describe the Bug**
Web version does not save settings

**To Reproduce**
Deploy docker web. Configure an arr and save. Open site in incognito window. Settings will be gone.

**Expected Behaviour**
Configuration persists

**Versions**
Web docker stable

**Comment by JagandeepBrar** [comment]
LunaSea is a client-side application, which means that all configuration options are saved in-browser. The Docker container simply hosts a compiled web application, essentially. It does not have a datastore.
