### ISSUE TITLE
[Bug] Notifications not working "Cannot GET /v1/custom/user/xxxxxxxx"

### ISSUE THREAD

**Issue by mdrayner** [JagandeepBrar/lunasea#781]
**Describe the Bug**
Notifications have stopped working.
Testing the URL produces the error:  "Cannot GET /v1/custom/user/xxxxxxxx" (same for device or any of the non custom notifications)

**To Reproduce**
Send a notification via Lunsea or
Enter a notification URL into a browser

**Expected Behaviour**
Notifications are sent

**Versions**
10.2.6 MacOs
iOS latest App Store version

Actually, this lookalike it could be an issue with Uptime Kuma.. have managed to get notifications working elsewhere but Uptime Kuma always reports "Error: getaddrinfo ENOTFOUND notify.lunasea.app"

**Comment by JagandeepBrar** [comment]
The notification webhooks must receive a `POST` request, not a `GET` request.

Further documentation: https://docs.lunasea.app/lunasea/notifications/custom-notifications

**Comment by moritz1000** [comment]
> The notification webhooks must receive a `POST` request, not a `GET` request.
> 
> Further documentation: [docs.lunasea.app/lunasea/notifications/custom-notifications](https://docs.lunasea.app/lunasea/notifications/custom-notifications)

I think @mdrayner just used to wrong words to describe their issue.

**I have the same problem! Notifcations used to work but stoped working about a week ago.**
When pressing the "Test" button in Sonarr no notification arrives. 
I did not change anything about my setup.
![image](https://github.com/JagandeepBrar/lunasea/assets/35174351/9e5c264f-28ab-4f97-9dd0-57757828b735)

**Comment by xifnet** [comment]
I can confirm that I have the same issue with Radarr 5.11.0.9244 and Sonarr 4.0.9.2244 running in a docker container. Notifications used to works for a year, and I think it stopped around last week. 

In my case it is a user notification such as `https://notify.lunasea.app/v1/sonarr/user/vxo...`. The error reported by Sonarr & Radarr is: 
```
Unable to send test message: Unable to post to webhook: HTTP request failed: [502:BadGateway] [POST] at [https://notify.lunasea.app/v1/sonarr/user/vxo...]
```
