### ISSUE TITLE
Actual Version on Builds.io

### ISSUE THREAD

**Issue by sysworx** [JagandeepBrar/LunaSea#8]
There is no actual version on Builds.io and on Altserver there is nothing of Lunasea.

**Comment by JagandeepBrar** [comment]
Here is the link to the BuildStore version: https://builds.io/apps/lunasea/

For AltStore, you must subscribe to the Patreon so you get the ability to sideload applications. Once you connect your Patreon account to AltStore, you can download the beta version of AltStore. Within the beta version of AltStore, you can hit the "+" in the top left of the "My Apps" tab to select the LunaSea IPA file (Downloadable under releases, or on the website) and get it installed on your device.

**Comment by sysworx** [comment]
Yes but its 0.1 at Builds and Guthaben says the ipa is higher 🤔
