### ISSUE TITLE
[Feature Request] A Way to Recognize torrent and Unset files more easily in search results 

### ISSUE THREAD

**Issue by ishalioh** [JagandeepBrar/LunaSea#84]
A way to recognize both Usenet and torrent files more easily, currently it’s written in grey as well as everything else, maybe a change of color like green for torrent and blue for Usenet would even be awesome.

**Comment by JagandeepBrar** [comment]
Hey there! Just added this feature into the branch `v1.1.0` (#135).

Will be live in TestFlight in the near future, and included in the next release!

![IMG_0796](https://user-images.githubusercontent.com/3048295/73882895-883fdd80-4828-11ea-9c80-5104b903fd02.PNG)

**Comment by ishalioh** [comment]
Thank you for the awesome app, I'm amazed that your still keeping this free, A donation link within the App would be an awesome addition too. One again thank you for the superb work.

**Comment by JagandeepBrar** [comment]
@ishalioh thanks for the kind words!

I don't want anyone to feel obligated to donate, but I have written a document here: https://docs.lunasea.app/development/donate

Gives some details on how to donate to me or on behalf of LunaSea to a nonprofit or charitable organization. I am more than happy to support LunaSea without financial support so give back to those that need the support :)

**Comment by ishalioh** [comment]
Will check it out, good sir. You are amazing 🙌

**Comment by JagandeepBrar** [comment]
Now available in TestFlight build: v1.1.0 (22)!
