### ISSUE TITLE
[Feature Request] Bazarr support

### ISSUE THREAD

**Issue by rodalpho** [JagandeepBrar/LunaSea#92]
I would like to see the Bazarr subtitle download client supported similarly to Radarr and Sonarr. 

https://www.bazarr.media/

**Comment by JagandeepBrar** [comment]
Bazarr support has already been requested and discussed here: https://github.com/JagandeepBrar/LunaSea/issues/42

**Comment by rodalpho** [comment]
Thank you, and sorry for the dupe!
