### ISSUE TITLE
[Feature Request] Multiple sonarr / radarr / lidarr support.

### ISSUE THREAD

**Issue by Silent-Remux** [JagandeepBrar/LunaSea#99]
**Describe the solution you'd like**

I run 3 or 4 of each for different purposes.

**Comment by JagandeepBrar** [comment]
Currently implemented through the "profiles" settings page.

You can create another profile where you can enter another instance's details. You can then switch between the profiles to view your different instances.

Currently there is no easy way to switch outside of the settings page, but I will be adding it to the drawer in the near future.
